### ISSUE TITLE
'/users/{user-id}' can't find user with existing user-id

### ISSUE THREAD

**Issue by cmaixen** [PubDig/pubdig#3]
When you login with a user and get redirected to the `/users/{user-id}` Y 
ou'll get an error on the GET-request.

![screen_shot_2015-02-24_at_15 32 11](https://cloud.githubusercontent.com/assets/2795893/6353707/416c5546-bc4b-11e4-99a2-efe19deafe11.png)

On the backend the following error pops up:
`{ status: 404, description: 'No user available for 1' }`
    
Very strange answer if you know that you just logged in with the user and got an acknowledgement. Also after manually checking in the database you can say for 100% that the user exists in the database.

**Comment by siverhae** [comment]
Fixed it by using left JOINS instead of inner JOINS
