### ISSUE TITLE
users without affiliation get a faulty affiliation anyway.

### ISSUE THREAD

**Issue by romeovs** [PubDig/pubdig#4]
When a user doesn't have any affiliations, `GET /users/:id` returns an affiliation with keys that point to `null`.

I expected:
```js
{
  "userId": 1,
  // ... 
  "affiliation": []
}
```

But now it is:
```js
{
  "userId": 1,
  // ... 
  "affiliation": {
    "id": null,
    "name": null,
    "place": null
  }
}
```

Also note that the affiliations should be an array instead of a single value.

**Comment by siverhae** [comment]
Fixed it by not returning affiliation when an affiliation does not exist, and gave back an array.
