### ISSUE TITLE
POST to /users (registering a user)

### ISSUE THREAD

**Issue by VincentDS** [PubDig/pubdig#9]
A POST to /users returns `{ description: 'E-mail must be a string', status: 400 }`, but however registers the user in the database with the correct e-mail.

**Comment by siverhae** [comment]
The database does not support multiple e-mail addresses at the moment, instead of giving an array of e-mail addresses you can give only one. I fixed the API.

**Comment by cmaixen** [comment]
Multiple e-mail addresses are currently not supported by our platform.
